spring:
    application:
        name: hospitalization2206818953
    datasource:
      url: jdbc:postgresql://localhost:15001/hospitalization2206818953
      username: postgres
      password: secret99
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update